services:
  arch:
    build:
      context: .
      dockerfile: ../../Dockerfile
    image: arch:1.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres-16
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oauth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - database
volumes:
  postgres_data:

networks:
  database:
    external: true
