app:
  name: "App"
  port: 8080
  log_level: 6
  prefork: false
  timezone: "Asia/Jakarta"
database:
  connection: "postgres"
  name: "oauth"
  username: "postgres"
  password: "postgres"
  host: "postgres_16"
  port: 5432
  timezone: "Asia/Jakarta"
  idle_connection: 10
  max_connection: 100
  max_life_time_connection: 600
redis:
  host: "redis_7"
  port: 6379
  db: 0
jwt:
  secret_key_access_token: "secret_key_access_token"
  secret_key_refresh_token: "secret_key_refresh_token"
  jwt_issuer: "jwt_issuer"
  expiration_access_token: "1h"
  expiration_refresh_token: "240h"
encrypted_key: "encrypted_key"
