services:
  app:
    image: ardizariat/goapp:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-app
    env_file:
      - .env
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    # command: air run cmd/web/main.go
    command: air
    restart: on-failure
    networks:
      - postgres-16_postgres_network
      - rabbitmq-4_rabbitmq_network
      - redis_redis_network

networks:
  postgres-16_postgres_network:
    external: true
  rabbitmq-4_rabbitmq_network:
    external: true
  redis_redis_network:
    external: true
