version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080" # Exposing Go app port
    environment:
      - DATABASE_HOST=postgres_16
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oauth
      - REDIS_HOST=redis_7
      - REDIS_PORT=6379
    networks:
      - database
volumes:
  postgres_data:

networks:
  database:
    external: true
