version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    image: ardizariat/app-golang:1.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=10.1.20.70
      - DATABASE_PORT=5432
      - DATABASE_USER=ardi
      - DATABASE_PASSWORD=modern888
      - DATABASE_NAME=oauth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-networks
    depends_on:
      - redis-app

  redis-app:
    image: redis:7.4.1
    container_name: redis-app
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
    networks:
      - app-networks

volumes:
  redis_data:

networks:
  app-networks:
