services:
  auth-backend-production:
    build:
        context: ../../
        dockerfile: docker/production/Dockerfile
    image: ardizariat/auth-backend:1.0
    container_name: auth-backend-production
    ports:
      - "9000:9000"
    restart: on-failure
    env_file:
      - .env
    networks:
      - postgres-16_postgres_network
      - rabbitmq-4_rabbitmq_network
      - redis_redis_network

networks:
  postgres-16_postgres_network:
    external: true
  rabbitmq-4_rabbitmq_network:
    external: true
  redis_redis_network:
    external: true
