// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"arch/internal/config"
	"arch/internal/delivery/http/controller"
	"arch/internal/delivery/http/middleware"
	"arch/internal/delivery/http/route"
	"arch/internal/gateway/producer"
	"arch/internal/repository"
	"arch/internal/usecase"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeServer() *fiber.App {
	viper := config.NewViper()
	logger := config.NewLogger(viper)
	db := config.NewDatabase(viper, logger)
	userRepository := repository.NewUserRepository(logger)
	client := config.NewRedis(viper)
	jwtWrapper := config.NewJwtWrapper(viper)
	rabbitMQClient := config.NewRabbitMQ(viper)
	rabbitMQProducer := producer.NewRabbitMQProducer(rabbitMQClient)
	authUseCase := usecase.NewAuthUseCase(db, userRepository, viper, logger, client, jwtWrapper, rabbitMQProducer)
	authJwtMiddleware := middleware.NewAuthJwtMiddleware(authUseCase)
	validate := config.NewValidator()
	authController := controller.NewAuthController(validate, logger, authUseCase)
	routeApp := route.NewRouteApp(authJwtMiddleware, authController)
	app := config.NewFiber(routeApp, viper)
	return app
}

// injector.go:

var configSet = wire.NewSet(config.NewViper, config.NewLogger, config.NewDatabase, config.NewValidator, config.NewRedis, config.NewJwtWrapper, config.NewRabbitMQ)

var repositorySet = wire.NewSet(repository.NewUserRepository)

var rabbitMQProducerSet = wire.NewSet(producer.NewRabbitMQProducer)

var useCaseSet = wire.NewSet(usecase.NewAuthUseCase)

var controllerSet = wire.NewSet(controller.NewAuthController)

var middlewareSet = wire.NewSet(middleware.NewAuthJwtMiddleware)
