services:
  auth-backend-development:
    build:
        context: ../../
        dockerfile: docker/staging/Dockerfile
    image: ardizariat/auth-backend:1.0
    container_name: auth-backend-development
    ports:
      - "9000:9000"
    environment:
      - DATABASE_HOST=postgres-16
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=oauth
      - REDIS_HOST=redis-7
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq-4
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    restart: on-failure
    networks:
      - postgres-16_postgres_network
      - rabbitmq-4_rabbitmq_network
      - redis_redis_network

networks:
  postgres-16_postgres_network:
    external: true
  rabbitmq-4_rabbitmq_network:
    external: true
  redis_redis_network:
    external: true
